### ISSUE TITLE
On completion of session, data of the previous session are not reset to null

### ISSUE THREAD

**Issue by Pratyush2703** [piyushjain2/confmgmt-ca#1]
Description:
    When the maintainer logs into the system a second time, the values in the total cash field persist from the previous login

Steps to reproduce:
1. Log into the maintenance system.
2. Click on "Show Total Cash Held"
3. The total cash held by the machine is noted
4. Click on "Press to collect all cash"
5. Click on "Door Locked" to secure the session
6. Click on "Press here when finished" to end session
7. The "Total cash" field and the "Collect cash" field persist to show values when greyed out
8. Log in to maintenance system
9. The "Total cash" field persists to show values from previous session

![image](https://user-images.githubusercontent.com/36813309/45608980-52118a80-ba88-11e8-95e5-6341b8df7bea.png)

![image](https://user-images.githubusercontent.com/36813309/45608967-3f975100-ba88-11e8-99e2-8e97c51bb2c7.png)

![image](https://user-images.githubusercontent.com/36813309/45608988-65245a80-ba88-11e8-9a07-2c4cd00baed1.png)

![image](https://user-images.githubusercontent.com/36813309/45608952-2ee6db00-ba88-11e8-8512-0ed379fb7686.png)

**Comment by nhatdx** [comment]
Analysis:
Affected file: MaintenanceController.java
A bug in the function logoutMaintainer need to be fixed

**Comment by akshayh696** [comment]
The Change is approved and should be taken by @manhpd

**Comment by manhpd** [comment]
Ok I am woriking on it!

**Comment by manhpd** [comment]
Bug fixed and push to Defect Branch, please review @piyushjain2

**Comment by piyushjain2** [comment]
Hi @Pratyush2703 ,

@manhpd has done the required changes, kindly review and tell.

**Comment by Pratyush2703** [comment]
The issue was tested using the reproduction procedure and the bugs have been resolved. Logging in as the maintainer no longer shows "Collect Cash" and "Total Cash" fields with persisting values. The issue can now be closed

![image](https://user-images.githubusercontent.com/36813309/45613163-01a22900-ba98-11e8-838b-28607b23e536.png)

![image](https://user-images.githubusercontent.com/36813309/45613174-06ff7380-ba98-11e8-8427-4dfff593acba.png)

![image](https://user-images.githubusercontent.com/36813309/45613180-0bc42780-ba98-11e8-8b19-00eda6b14121.png)
